In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data1 = pd.read_csv("./Dataset/part-00000-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv")

In [2]:
X = data1.iloc[:, :-1].values
yi = data1.iloc[:, -1].values
print(X)
print(yi)


[[0.00000000e+00 5.40000000e+01 6.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.41550000e+02]
 [0.00000000e+00 5.70400000e+01 6.33000000e+00 ... 1.60987842e+02
  5.00000000e-02 1.41550000e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.41550000e+02]
 ...
 [7.85260201e-04 5.62900000e+01 6.11000000e+00 ... 6.71167282e-01
  3.00000000e-02 1.41550000e+02]
 [9.01250839e-04 7.20900000e+01 6.11000000e+00 ... 5.59942239e+01
  1.70000000e-01 1.41550000e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.41550000e+02]]
['DDoS-RSTFINFlood' 'DoS-TCP_Flood' 'DDoS-ICMP_Flood' ... 'DDoS-SYN_Flood'
 'DDoS-PSHACK_Flood' 'DDoS-ICMP_Flood']


In [5]:
# from sklearn.impute import SimpleImputer
# imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# imputer.fit(X[:, 1:3])

# X[:, 1:3] = imputer.transform(X[:, 1:3])

data1.describe()
data1.shape[1]

47

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

y = np.array(yi).reshape(-1, 1)

attack_types =["Benign", "Backdoor", "Hijacking", "Injection", "DDoS",  "DoS", 
                         "BruteForce", "Mirai", "Spoofing", "Recon", "XSS"]

label_mapping = {}

# Init
encode = OneHotEncoder(sparse=False)

# Mã hóa dữ liệu
y_encoded = encode.fit_transform(y)

# lấy list label
labels = encode.categories_[0]

## mapping
for label in labels:
    label_mapping[label]= -1
    for inx, type in enumerate(attack_types):
        if label.find(type)!=-1:
            label_mapping[label] = inx
            break

print(label_mapping)

# benign_index = np.where(labels == "BenignTraffic")[0][0]

# y_transed = 1 - y_encoded[:, benign_index]

# print (y_transed)
for i, value in enumerate(yi):
    yi[i]= label_mapping.get(value, -1)

print(yi)

{'Backdoor_Malware': 1, 'BenignTraffic': 0, 'BrowserHijacking': 2, 'CommandInjection': 3, 'DDoS-ACK_Fragmentation': 4, 'DDoS-HTTP_Flood': 4, 'DDoS-ICMP_Flood': 4, 'DDoS-ICMP_Fragmentation': 4, 'DDoS-PSHACK_Flood': 4, 'DDoS-RSTFINFlood': 4, 'DDoS-SYN_Flood': 4, 'DDoS-SlowLoris': 4, 'DDoS-SynonymousIP_Flood': 4, 'DDoS-TCP_Flood': 4, 'DDoS-UDP_Flood': 4, 'DDoS-UDP_Fragmentation': 4, 'DNS_Spoofing': 8, 'DictionaryBruteForce': 6, 'DoS-HTTP_Flood': 5, 'DoS-SYN_Flood': 5, 'DoS-TCP_Flood': 5, 'DoS-UDP_Flood': 5, 'MITM-ArpSpoofing': 8, 'Mirai-greeth_flood': 7, 'Mirai-greip_flood': 7, 'Mirai-udpplain': 7, 'Recon-HostDiscovery': 9, 'Recon-OSScan': 9, 'Recon-PingSweep': 9, 'Recon-PortScan': 9, 'SqlInjection': 3, 'Uploading_Attack': -1, 'VulnerabilityScan': -1, 'XSS': 10}
[4 5 4 ... 4 4 4]


c:\Users\hoang\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [5]:
print(tf.test.is_built_with_cuda())  # True nếu có hỗ trợ CUDA
print(tf.test.is_gpu_available())  # True nếu GPU đang được dùng

False
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
False


In [13]:
from tensorflow.keras.utils import to_categorical
import numpy as np

#One Hot Encoder
yi = np.array(yi)
print(yi)

num_classes = len(label_mapping)
y_encoded = to_categorical(yi, num_classes)

print(y_encoded)

[4 5 4 ... 4 4 4]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
