In [8]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data1 = pd.read_csv("D:/DoAnChuyenNganh_Train/Dataset/part-00051-363d1ba3-8ab5-4f96-bc25-4d5862db7cb9-c000.csv")

In [9]:
X = data1.iloc[:, :-1].values
yi = data1.iloc[:, -1].values
print(X)
print(yi)

[[9.36701460e+00 1.88380000e+02 6.00000000e+00 ... 6.84483674e-01
  2.30000000e-01 1.41550000e+02]
 [2.41289905e+00 1.18800000e+02 6.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.41550000e+02]
 [0.00000000e+00 5.40000000e+01 6.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.41550000e+02]
 ...
 [4.04614724e+01 2.01451000e+04 1.37000000e+01 ... 5.84749536e+03
  8.00000000e-01 3.85000000e+01]
 [1.13391414e-01 8.61617400e+04 1.70000000e+01 ... 3.11678812e+05
  9.50000000e-01 1.41550000e+02]
 [4.01919842e-03 5.45400000e+01 6.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.41550000e+02]]
['DoS-SYN_Flood' 'DDoS-SynonymousIP_Flood' 'DDoS-SYN_Flood' ...
 'BenignTraffic' 'DDoS-UDP_Fragmentation' 'DDoS-TCP_Flood']


In [10]:
# from sklearn.impute import SimpleImputer
# imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# imputer.fit(X[:, 1:3])

# X[:, 1:3] = imputer.transform(X[:, 1:3])

data1.describe()
data1.shape[1]

47

In [11]:
#label theo Dos, DDos
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

y = np.array(yi).reshape(-1, 1)

attack_types =["Benign", "Backdoor", "Hijacking", "Injection", "DDoS",  "DoS", 
                         "BruteForce", "Mirai", "Spoofing", "Recon", "XSS"]

label_mapping = {}

# Init
encode = OneHotEncoder()

# Mã hóa dữ liệu
y_encoded = encode.fit_transform(y)

# lấy list label
labels = encode.categories_[0]

print(labels)

print("Len Label", len(labels))

list_dos = []
for label in labels:
    if label.find("DoS")!=-1:
        list_dos.append(label)

print(list_dos)

print("len dos", len(list_dos))

['Backdoor_Malware' 'BenignTraffic' 'BrowserHijacking' 'CommandInjection'
 'DDoS-ACK_Fragmentation' 'DDoS-HTTP_Flood' 'DDoS-ICMP_Flood'
 'DDoS-ICMP_Fragmentation' 'DDoS-PSHACK_Flood' 'DDoS-RSTFINFlood'
 'DDoS-SYN_Flood' 'DDoS-SlowLoris' 'DDoS-SynonymousIP_Flood'
 'DDoS-TCP_Flood' 'DDoS-UDP_Flood' 'DDoS-UDP_Fragmentation' 'DNS_Spoofing'
 'DictionaryBruteForce' 'DoS-HTTP_Flood' 'DoS-SYN_Flood' 'DoS-TCP_Flood'
 'DoS-UDP_Flood' 'MITM-ArpSpoofing' 'Mirai-greeth_flood'
 'Mirai-greip_flood' 'Mirai-udpplain' 'Recon-HostDiscovery' 'Recon-OSScan'
 'Recon-PingSweep' 'Recon-PortScan' 'SqlInjection' 'Uploading_Attack'
 'VulnerabilityScan' 'XSS']
Len Label 34
['DDoS-ACK_Fragmentation', 'DDoS-HTTP_Flood', 'DDoS-ICMP_Flood', 'DDoS-ICMP_Fragmentation', 'DDoS-PSHACK_Flood', 'DDoS-RSTFINFlood', 'DDoS-SYN_Flood', 'DDoS-SlowLoris', 'DDoS-SynonymousIP_Flood', 'DDoS-TCP_Flood', 'DDoS-UDP_Flood', 'DDoS-UDP_Fragmentation', 'DoS-HTTP_Flood', 'DoS-SYN_Flood', 'DoS-TCP_Flood', 'DoS-UDP_Flood']
len dos 16


In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

y = np.array(yi).reshape(-1, 1)

attack_types =["Benign", "Backdoor", "Hijacking", "Injection", "DDoS",  "DoS", 
                         "BruteForce", "Mirai", "Spoofing", "Recon", "XSS"]

label_mapping = {}

# Init
encode = OneHotEncoder(sparse=False)

# Mã hóa dữ liệu
y_encoded = encode.fit_transform(y)

# lấy list label
labels = encode.categories_[0]

## mapping
for label in labels:
    label_mapping[label]= -1
    for inx, type in enumerate(attack_types):
        if label.find(type)!=-1:
            label_mapping[label] = inx
            break

print(label_mapping)

# benign_index = np.where(labels == "BenignTraffic")[0][0]

# y_transed = 1 - y_encoded[:, benign_index]

# print (y_transed)
for i, value in enumerate(yi):
    yi[i]= label_mapping.get(value, -1)

print(yi)

{'Backdoor_Malware': 1, 'BenignTraffic': 0, 'BrowserHijacking': 2, 'CommandInjection': 3, 'DDoS-ACK_Fragmentation': 4, 'DDoS-HTTP_Flood': 4, 'DDoS-ICMP_Flood': 4, 'DDoS-ICMP_Fragmentation': 4, 'DDoS-PSHACK_Flood': 4, 'DDoS-RSTFINFlood': 4, 'DDoS-SYN_Flood': 4, 'DDoS-SlowLoris': 4, 'DDoS-SynonymousIP_Flood': 4, 'DDoS-TCP_Flood': 4, 'DDoS-UDP_Flood': 4, 'DDoS-UDP_Fragmentation': 4, 'DNS_Spoofing': 8, 'DictionaryBruteForce': 6, 'DoS-HTTP_Flood': 5, 'DoS-SYN_Flood': 5, 'DoS-TCP_Flood': 5, 'DoS-UDP_Flood': 5, 'MITM-ArpSpoofing': 8, 'Mirai-greeth_flood': 7, 'Mirai-greip_flood': 7, 'Mirai-udpplain': 7, 'Recon-HostDiscovery': 9, 'Recon-OSScan': 9, 'Recon-PingSweep': 9, 'Recon-PortScan': 9, 'SqlInjection': 3, 'Uploading_Attack': -1, 'VulnerabilityScan': -1, 'XSS': 10}
[4 5 4 ... 4 4 4]


c:\Users\hoang\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [5]:
print(tf.test.is_built_with_cuda())  # True nếu có hỗ trợ CUDA
print(tf.test.is_gpu_available())  # True nếu GPU đang được dùng

False
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
False


In [13]:
from tensorflow.keras.utils import to_categorical
import numpy as np

#One Hot Encoder
yi = np.array(yi)
print(yi)

num_classes = len(label_mapping)
y_encoded = to_categorical(yi, num_classes)

print(y_encoded)

[4 5 4 ... 4 4 4]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [2]:
import pycuda.driver as cuda
import pycuda.autoinit

# Kiểm tra phiên bản CUDA
print(f"Phiên bản Driver CUDA: {cuda.get_driver_version() // 1000}.{cuda.get_driver_version() % 1000 // 10}")
import tensorflow as tf
print("GPUs Available: ", tf.config.list_physical_devices('GPU'))


Phiên bản Driver CUDA: 12.8
GPUs Available:  []
